# Use these commands to generate the ESPResSo input script and data file
# (and other auxilliary files):

cd emoltemplate_files/    # (The .et input files are in this directory)

  # run emoltemplate

  emoltemplate.sh system.et

  # This will generate one (or perhaps more) TCL files:
  # These files are the input files directly read by ESPResSo.  Move them to 
  # the parent directory (or wherever you plan to run the simulation).

  mv -f system.tcl ../

  # Optional:
  # The "./output_ttree/" directory is full of temporary files generated by 
  # emoltemplate. They can be useful for debugging, but are usually thrown away.
  rm -rf output_ttree/

cd ../


# IMPORTANT: For this example to work, Espresso must be compiled with 
#            the "BOND_CONSTRAINT" feature enabled.
#            (Edit your myconfig.h file and make sure it contains this line:
#                  #define BOND_CONSTRAINT
#             If necessary, copy src/myconfig-default.h to myconfig.h
#             and then add this line.)

