# Use these commands to generate the LAMMPS input script and data file
# (and other auxilliary files):


# Create LAMMPS input files this way:
cd emoltemplate_files

  # run moltemplate

  emoltemplate.sh system.et

  # This will generate one (or perhaps more) TCL files:
  # These files are the input files directly read by ESPResSo.  Move them to 
  # the parent directory (or wherever you plan to run the simulation).

  mv -f system.tcl ../

  # Optional:
  # The "./output_ttree/" directory is full of temporary files generated by 
  # moltemplate.  They can be useful for debugging, but are usually thrown away.
  rm -rf output_ttree/

cd ../
